### ISSUE TITLE
failure to login to GitHub

### ISSUE THREAD

**Issue by varioustoxins** [dsoftwareinc/ghactions-manager#164] opened 2024-06-12 08:04 UTC
I seem to be no longer able to login to GitHub either using tokens or login 

![image](https://github.com/dsoftwareinc/ghactions-manager/assets/3621369/504da391-73d3-41a0-8587-7b7251c312f6)

have  installed and uninstalled and refreshed tokens

tokens have these permissions

gist, read:org, read:user, repo, user:email, workflow

Plugin version: 2024.2.1 [seems to occur after latest update]
IDE: PyCharm
OS: macOS Sonoma

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/164">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/164/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/164/pledge.svg">
</picture>
</a>

**Comment by dmitri-danilov** [comment] 2024-06-12 08:15
Having the same issue (and the same setup!) - was just going to report it and discovered I'm not the only one.

**Comment by cunla** [comment] 2024-06-12 12:14
Thanks for reporting. I'll address it this weekend

**Comment by cunla** [comment] 2024-06-12 14:36
which version of pycharm are you using?

**Comment by varioustoxins** [comment] 2024-06-12 19:10
2024.1
BUILD #PY-241.14494.241 professional

Dr Gary S Thompson NMR Facility Manager
CCPN CoI & Working Group Member
Wellcome Trust Biomolecular NMR Facility
School of Biosciences,  Division of Natural Sciences
University of Kent,  Canterbury,  Kent,  England,  CT2 7NZ

☎:01227 82 7117
✉️: ***@***.***
orchid: orcid.org/0000-0001-9399-7636

On 12 Jun 2024, at 15:37, Daniel M ***@***.***> wrote:


CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.




which version of pycharm are you using?

**Comment by cunla** [comment] 2024-06-13 18:23
- If you checkout any open-source open repository, can you see its workflows?
- Can you provide the relevant logs of pycharm? (Help -> sHOW logs -> all lines with `com.dsoftware...`
- Can you access the other repositories you have defined? (I see in the snapshot you have 4 repositories)
- If you use github settings -> can you remove the account and re-login and check?


I suspect that the organization hosting these repositories is preventing using GitHub REST API and that's why you are getting this message, though I need further information to be 100% sure.

If that is the case, you need to approach your GitHub org admin to enable using REST API.

**Comment by cunla** [comment] 2024-06-13 18:38
If you generate a custom token with access to REST API and configure it instead of using GitHub settings, does it work?

**Comment by dmitri-danilov** [comment] 2024-06-13 22:07
Same error, irrespectively of whether GitHub settings or GitHub token is used in config. Token verified with Postman and GitHub **/repos/handwai-org/handwai-web/actions/runs** endpoint - expected results returned.
Logs from PyCharm:

2024-06-13 23:58:22,225 [29409189]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Updating collaborators list: https://api.github.com/repos/handwai-org/handwai-web/collaborators?page=1&per_page=100
2024-06-13 23:58:22,225 [29409189]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Updating workflow types: https://api.github.com/repos/handwai-org/handwai-web/actions/workflows?page=1&per_page=100
2024-06-13 23:58:22,225 [29409189]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Calling https://api.github.com/repos/handwai-org/handwai-web/actions/runs?page=1&per_page=30
2024-06-13 23:58:22,225 [29409189]   INFO - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Updating branches list: https://api.github.com/repos/handwai-org/handwai-web/branches?page=1&per_page=100
2024-06-13 23:58:22,679 [29409643]   WARN - #com.dsoftware.ghmanager.data.WorkflowRunListLoader - Error loading workflow runs from https://api.github.com/repos/handwai-org/handwai-web/actions/runs?page=1&per_page=30
2024-06-13 23:58:22,682 [29409646]   WARN - #com.dsoftware.ghmanager.ui.panels.wfruns.WorkflowRunsListPanel - Got error when getting workflow-runs: org.jetbrains.plugins.github.exceptions.GithubAuthenticationException: Request response: Access to this site has been restricted. If you believe this is an error, please contact https://support.github.com.

**Comment by varioustoxins** [comment] 2024-06-14 09:31
Hi

My repo is open source


<https://github.com/varioustoxins/NEF-Pipelines>
[NEF-Pipelines.png]
varioustoxins/NEF-Pipelines: Nef tools<https://github.com/varioustoxins/NEF-Pipelines>
github.com<https://github.com/varioustoxins/NEF-Pipelines>


regards
Gary

Dr Gary S Thompson NMR Facility Manager
CCPN CoI & Working Group Member
Wellcome Trust Biomolecular NMR Facility
School of Biosciences,  Division of Natural Sciences
University of Kent,  Canterbury,  Kent,  England,  CT2 7NZ

☎:01227 82 7117
✉️: ***@***.***
orchid: orcid.org/0000-0001-9399-7636

On 13 Jun 2024, at 19:23, Daniel M ***@***.***> wrote:


CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.




  *   If you checkout any open-source open repository, can you see its workflows?
  *   Can you provide the relevant logs of pycharm? (Help -> sHOW logs -> all lines with com.dsoftware...
  *   Can you access the other repositories you have defined? (I see in the snapshot you have 4 repositories)
  *   If you use github settings -> can you remove the account and re-login and check?

I suspect that the organization hosting these repositories is preventing using GitHub REST API and that's why you are getting this message, though I need further information to be 100% sure.

If that is the case, you need to approach your GitHub org admin to enable using REST API.

**Comment by cunla** [comment] 2024-06-14 12:24
Hi,

There are 2 different issues at play.

@dmitri-danilov - 
As you can see on the logs, the issue is clearly the permissions of the token you are using. The requests to get branches/workflows/collaborators pass while the request to get runs gives an error. I recommend creating a new token manually (GitHub Account settings -> Developer settings -> Personal Access Tokens -> Classic -> Check repo permissions. See [here](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-workflow)

> OAuth app tokens and personal access tokens (classic) need the repo scope to use this endpoint with a private repository.

Alternatively, if you want to use fine-grained token:
> [Fine-grained access tokens for "List workflow runs for a workflow"](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-workflow--fine-grained-access-tokens)
> This endpoint works with the following fine-grained token types:
> [GitHub App user access tokens](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-user-access-token-for-a-github-app)
[GitHub App installation access tokens](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app)
> [Fine-grained personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token)

@varioustoxins - 
- The repo in the snapshot is different than the repo you sent, but I assume the one in the snapshot is [this one](https://github.com/varioustoxins/PyNMRSTAR) which is also open-source. 
- For the repo you sent, one does not need any token to view the workflow-runs (just go to: https://api.github.com/repos/varioustoxins/NEF-Pipelines/actions/runs) - so I doubt there are issues with the plugin viewing runs for it. Assuming the other one is also opwn-source, then similarly, https://api.github.com/repos/varioustoxins/PyNMRSTAR/actions/runs shows the workflow-runs without a token (there are no workflow runs). 
- I also cloned the repos and can see workflow runs on my pycharm. (see snapshot below)
- Therefore, the issue you are experiencing is different.
- Would you mind scheduling a quick debugging session with me to understand the issue better? my email daniel at moransoftware.ca

![image](https://github.com/dsoftwareinc/ghactions-manager/assets/3419721/4c5d6c7b-ec79-4a80-8b2d-55485ead36d2)

**Comment by dmitri-danilov** [comment] 2024-06-14 13:36
> @dmitri-danilov -
> As you can see on the logs, the issue is clearly the permissions of the token you are using. The requests to get branches/workflows/collaborators pass while the request to get runs gives an error. I recommend creating a new token manually (GitHub Account settings -> Developer settings -> Personal Access Tokens -> Classic -> Check repo permissions. See [here](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-workflow)

This is Postman configured to use that same token in the 'Authorization' header and pulling workflow runs using the same URL as in the logs:

<img width="1090" alt="image" src="https://github.com/dsoftwareinc/ghactions-manager/assets/165052179/a3da011d-c658-44c5-a0b0-3131eee01baa">

**Comment by cunla** [comment] 2024-06-14 13:42
@dmitri-danilov 
Ok, this helps. I believe I figured out your issue. How come you have `token ghp_...` and not `Bearer ghp_...` in your Authorization header? Is this custom settings? 
If you change it to `Bearer ghp_...` does it work?

The plugin uses `com.intellij.util.io.HttpSecurityUtil.createBearerAuthHeaderValue` which creates `Bearer ...` header which is based on [GitHub documentation](https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28#about-authentication)

**Comment by dmitri-danilov** [comment] 2024-06-14 14:09
> @dmitri-danilov Ok, this helps. I believe I figured out your issue. How come you have `token ghp_...` and not `Bearer ghp_...` in your Authorization header? Is this custom settings? If you change it to `Bearer ghp_...` does it work?
> 
> The plugin uses `com.intellij.util.io.HttpSecurityUtil.createBearerAuthHeaderValue` which creates `Bearer ...` header which is based on [GitHub documentation](https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28#about-authentication)

Just tried with Bearer:

<img width="1087" alt="image" src="https://github.com/dsoftwareinc/ghactions-manager/assets/165052179/3076e7d0-2448-45d4-8c81-5b3bdc001a76">

I think I googled a couple of examples where it was "token" yesterday which surprised me because documentation clearly said "Bearer". Then I was silly enough to ask ChatGPT and it also said "token". :))
As we can see, both appear to be supported and surprisingly, both are working. Wondering if they retained support for "token" for backward compatibility or something.

**Comment by dmitri-danilov** [comment] 2024-06-15 09:55
Hey Dan,

I have found the root cause and you are not gonna believe this.
I have set up a local HTTP proxy to trace and compare HTTP requests produced by your plugin and Postman. Soon I discovered that the problem was caused by the value of the "User-Agent" header - "Intellij IDEA Github Plugin"! If I remove the header totally or change even a single char in it - it works, if I restore it to the original value - 403 error is returned. So it really looks like "Intellij IDEA Github Plugin" User-Agent is blacklisted in GitHub for whatever reason.

You are welcome :)

**Comment by cunla** [comment] 2024-06-15 12:25
Unbelievable!!!
What I don't get is how does it work for others? Are you using classic tokens or fine grained tokens?
Do you mind trying the other option? I will update it to not use user agent but I will reach out to GitHub as well.

**Comment by cunla** [comment] 2024-06-15 15:22
I pushed a fix and submitted a new version that allows changing the user-agent in the plugin settings.
Thanks again for reporting this and helping to debug the root cause.

**Comment by cunla** [comment] 2024-06-15 15:23
![image](https://github.com/dsoftwareinc/ghactions-manager/assets/3419721/ccb020c4-ad5e-42ef-9abf-690817d8d6df)

**Closed by cunla** 2024-06-15 15:22 UTC

**Comment by vladimir-ilnytskyi** [comment] 2024-06-15 19:57
Hey, in my org settings i have this only related to jetbrains products:

<img width="1513" alt="image" src="https://github.com/dsoftwareinc/ghactions-manager/assets/94364525/aec7abd7-9a12-4635-b8b1-753892323233">

**Comment by varioustoxins** [comment] 2024-06-18 21:13
Fixed for me now ;-)

regards
Gary

Dr Gary S Thompson NMR Facility Manager
CCPN CoI & Working Group Member
Wellcome Trust Biomolecular NMR Facility
School of Biosciences,  Division of Natural Sciences
University of Kent,  Canterbury,  Kent,  England,  CT2 7NZ

☎:01227 82 7117
✉️: ***@***.***
orchid: orcid.org/0000-0001-9399-7636

On 15 Jun 2024, at 20:57, vladimir-ilnytskyi ***@***.***> wrote:


CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.




Hey, in my org settings i have this only related to jetbrains products:

image.png (view on web)<https://github.com/dsoftwareinc/ghactions-manager/assets/94364525/aec7abd7-9a12-4635-b8b1-753892323233>

**Comment by cunla** [comment] 2024-06-18 21:19
Great! Thanks for reporting the bug!
