### ISSUE TITLE
No git repositories in project

### ISSUE THREAD

**Issue by stormcrow85** [dsoftwareinc/ghactions-manager#162] opened 2024-06-03 16:34 UTC
### Describe the bug
It seems like the plugin doesn't recognize my repos. I have 2 in my project (none of them is in the root folder). Plugin pane shows "No git repositories in project".

### Steps to reproduce
Installed plugin through the Marketplace. Tried uninstalling, restating and re-installing several times.

### Expected behavior
Well.. the plugin should identify my repos, I think :)

### Additional context

Plugin version: 2024.2.0
IDE: PhpStorm 2024.1
OS: Windows 10

![image](https://github.com/dsoftwareinc/ghactions-manager/assets/4579192/5b97af73-9acb-496c-8651-87b77357b172)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/162">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/162/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/162/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment] 2024-06-03 16:42
Hi @stormcrow85, thanks for reporting this.

Generally speaking, the plugin takes the repositories from PhpStorm. 

- Can you check if you go to the Menu: `git` -> `Manage remotes` what do you have listed?
- If you go to the git tool window, what do you see there?

**Comment by stormcrow85** [comment] 2024-06-03 16:55
Hi @cunla, thanks for the quick response!

- In `Git` -> `Manage Remotes` I see my repos listed as expected
- In the Git tool window I can see my commits history, local changes etc.
So it does seem that PhpStorm is identifying my repos. I also made sure my account is connected and have the correct permissions under `Settings` -> `Version Control` -> `GitHub`

**Comment by cunla** [comment] 2024-06-03 17:12
Can you see pull-requests in the Pull-Requests tool-window?

**Comment by stormcrow85** [comment] 2024-06-03 18:23
I am not using pull requests in my project, so I don't see this tool.
I also tried generating a new token from GitHub in case token formats were changed. Uninstalled and reinstalled and still getting the same result.

In the plugin settings I tried both "Use GitHub accounts settings?" checked and unchecked with my token, and still no luck.

**Comment by cunla** [comment] 2024-06-03 18:28
The issue is not your GitHub settings, otherwise it would show you a message `GitHub account not configured and no API Token`.
The issue is there are no repositories configured in the PhpStorm level.
I recommend perhaps deleting the `.idea` folder and recreating the project.

**Comment by cunla** [comment] 2024-06-04 17:30
Any update?

**Comment by stormcrow85** [comment] 2024-06-04 19:20
I tried deleting the `.idea` folder, didn't help

**Comment by cunla** [comment] 2024-06-04 19:48
- Do you know how to enable debug logs on PhpStorm?
- Does it happen on other projects?
- Would you mind having a video-call share screen so I can see what's going on?

**Comment by stormcrow85** [comment] 2024-06-06 14:16
> * Do you know how to enable debug logs on PhpStorm?
I did. Here is my Custom Debug Log Configuration:
![image](https://github.com/dsoftwareinc/ghactions-manager/assets/4579192/d9a21527-8d3d-41ea-b3ce-c4e309ea3b4f)

> * Does it happen on other projects?
I have one project that doesn't use GitHub actions, but I at least see the plugins UI and it's showing my repos.  It's giving me "Can't load workflow runs" which of course makes sense because it doesn't have any.

> * Would you mind having a video-call share screen so I can see what's going on?
Sure!

**Comment by cunla** [comment] 2024-06-06 14:20
Please book some time with me - https://cal.com/daniel-moran/work-meeting

**Comment by cunla** [comment] 2024-06-06 17:11
Caused by git remote not being a valid URL. 
Investigate how identify these.

**Comment by cunla** [comment] 2024-06-07 13:16
Resolved by improving the message shown when there are no repositories in the project.
Will be included in the next version.

**Closed** 2024-06-13 18:48 UTC

**Comment by thisi5patrick** [comment] 2026-08-31 09:53
@cunla I'm currently having the same issue, even though I do have git set up and everything in my project. 

<img width="496" height="50" alt="Image" src="https://github.com/user-attachments/assets/51ae0375-a716-47f8-9cfb-d47aaf21fd0e" />
<br>
<img width="256" height="138" alt="Image" src="https://github.com/user-attachments/assets/036fd85a-f049-4d1d-96f5-dd0fcb0847ef" />

I have tried removing the `.idea` folder, reinstalling the plugin and invalidating the caches through the IDE

Plugin version: 2026.1.10
IDE: PyCharm 2026.1.3
OS: macOS 26.6
